theme = "katsumeshi"

[editor]
true-color = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
C-s = ":w" 
C-o = ":open ~/.conig/helix/config.toml"
C-r = ":config-reload"